- name: validate certificate
  include_tasks: generate.yml
  with_items: "{{ letsencrypt_domains }}"
- name: insert intermediate and root certificate
  include_tasks: intermediate.yml
  with_items: "{{ letsencrypt_domains }}"
